# Generated by Django 5.0.3 on 2024-04-13 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_fuelrecieved_fueltype_vehicle_fueltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuelType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.fueltype'),
        ),
    ]
