# Generated by Django 5.0.3 on 2024-04-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicle_fueltype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fueltype',
            old_name='name',
            new_name='fuel_name',
        ),
    ]
